# Generated by Django 4.1.5 on 2023-01-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descriptiion',
            new_name='description',
        ),
    ]
